export const githubLanguageToTechMapKey: Record<string, string> = {
  "TypeScript": "typescript",
  "JavaScript": "javascript",
  "HTML": "html5",
  "CSS": "css3",
  "Shell": "bash",
  "Python": "python",
  "C++": "cpp",
  "C#": "csharp",
  "C": "c",
  "Java": "java",
  "Go": "go",
  "Rust": "rust",
  "Ruby": "ruby",
  "PHP": "php",
  "Swift": "swift",
  "Kotlin": "kotlin",
  "Dart": "dart",
  "Vue": "vuejs",
  "Svelte": "svelte",
  "Jupyter Notebook": "python",
  "SCSS": "css3",
  "Less": "css3"
};
