import { TechItem } from "@/types/tech.types";

export const techStack: TechItem[] = [
  {
    id: "react",
    name: "React",
    badge: "react_js.svg",
    icon: "react-icon.svg",
    category: "Frontend",
    tags: ["react", "frontend"],
  },
  {
    id: "react_native",
    name: "React Native",
    badge: "react_native.svg",
    icon: "react-icon.svg",
    category: "Uncategorized",
    tags: ["react_native", "uncategorized"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    badge: "next_js.svg",
    icon: "nextjs-icon.svg",
    category: "Frontend",
    tags: ["nextjs", "frontend"],
  },
  {
    id: "angular",
    name: "Angular",
    badge: "angular.svg",
    icon: "angular-icon.svg",
    category: "Frontend",
    tags: ["angular", "frontend"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    badge: "typescript.svg",
    icon: "typescript-icon.svg",
    category: "Frontend",
    tags: ["typescript", "frontend"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    badge: "javascript.svg",
    icon: "javascript-icon.svg",
    category: "Frontend",
    tags: ["javascript", "frontend"],
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    badge: "tailwind_css.svg",
    icon: "tailwind-icon.svg",
    category: "Frontend",
    tags: ["tailwindcss", "frontend"],
  },
  {
    id: "redux",
    name: "Redux",
    badge: "redux.svg",
    icon: "redux-icon.svg",
    category: "Frontend",
    tags: ["redux", "frontend"],
  },
  {
    id: "zustand",
    name: "Zustand",
    badge: "zustand.svg",
    icon: "zustand-icon.svg",
    category: "Frontend",
    tags: ["zustand", "frontend"],
  },
  {
    id: "mui",
    name: "MUI",
    badge: "mui.svg",
    icon: "mui-icon.svg",
    category: "Frontend",
    tags: ["mui", "frontend"],
  },
  {
    id: "chakra",
    name: "Chakra",
    badge: "chakra_ui.svg",
    icon: "chakraui-icon.svg",
    category: "Frontend",
    tags: ["chakra", "frontend"],
  },
  {
    id: "python",
    name: "Python",
    badge: "python.svg",
    icon: "python-icon.svg",
    category: "Backend",
    tags: ["python", "backend"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    badge: "nodejs.svg",
    icon: "node-js-icon.svg",
    category: "Backend",
    tags: ["nodejs", "backend"],
  },
  {
    id: "nestjs",
    name: "NestJS",
    badge: "nestjs.svg",
    icon: "nestjs-icon.svg",
    category: "Backend",
    tags: ["nestjs", "backend"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    badge: "postgresql.svg",
    icon: "postgresql-icon.svg",
    category: "Databases",
    tags: ["postgresql", "databases"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    badge: "mongodb.svg",
    icon: "mongodb-icon.svg",
    category: "Databases",
    tags: ["mongodb", "databases"],
  },
  {
    id: "sqlite",
    name: "Sqlite",
    badge: "sqlite.svg",
    icon: "sqlite-icon.svg",
    category: "Databases",
    tags: ["sqlite", "databases"],
  },
  {
    id: "dynamodb",
    name: "Dynamodb",
    badge: "dynamodb.svg",
    icon: "dynamodb-icon.svg",
    category: "Databases",
    tags: ["dynamodb", "databases"],
  },
  {
    id: "supabase",
    name: "Supabase",
    badge: "supabase.svg",
    icon: "supabase-icon.svg",
    category: "Databases",
    tags: ["supabase", "databases"],
  },
  {
    id: "prisma",
    name: "Prisma",
    badge: "prisma.svg",
    icon: "prisma-icon.svg",
    category: "Databases",
    tags: ["prisma", "databases"],
  },
  {
    id: "typeorm",
    name: "Typeorm",
    badge: "typeorm.svg",
    icon: "typeorm-icon.svg",
    category: "Databases",
    tags: ["typeorm", "databases"],
  },
  {
    id: "aws",
    name: "AWS",
    badge: "aws.svg",
    icon: "aws-icon.svg",
    category: "Uncategorized",
    tags: ["aws", "uncategorized"],
  },
  {
    id: "terraform",
    name: "Terraform",
    badge: "terraform.svg",
    icon: "terraform-icon.svg",
    category: "Languages & Scripting",
    tags: ["terraform", "languagesscripting"],
  },
  {
    id: "aws_sam",
    name: "Aws Sam",
    badge: "aws_sam.svg",
    icon: "aws_sam-icon.svg",
    category: "Uncategorized",
    tags: ["aws_sam", "uncategorized"],
  },
  {
    id: "docker",
    name: "Docker",
    badge: "docker.svg",
    icon: "docker-icon.svg",
    category: "Uncategorized",
    tags: ["docker", "uncategorized"],
  },
  {
    id: "gitlab_ci",
    name: "Gitlab Ci",
    badge: "gitlab_ci.svg",
    icon: "gitlab-ci-icon.svg",
    category: "Uncategorized",
    tags: ["gitlab_ci", "uncategorized"],
  },
  {
    id: "github_actions",
    name: "Github Actions",
    badge: "github_actions.svg",
    icon: "github-actions-icon.svg",
    category: "Uncategorized",
    tags: ["github_actions", "uncategorized"],
  },
  {
    id: "vercel",
    name: "Vercel",
    badge: "vercel.svg",
    icon: "vercel-icon.svg",
    category: "Cloud & DevOps",
    tags: ["vercel", "clouddevops"],
  },
  {
    id: "html5",
    name: "HTML5",
    badge: "html5.svg",
    icon: "html5-icon.svg",
    category: "Frontend",
    tags: ["html5", "frontend"],
  },
  {
    id: "css3",
    name: "CSS3",
    badge: "css3.svg",
    icon: "css3-icon.svg",
    category: "Frontend",
    tags: ["css3", "frontend"],
  },
  {
    id: "radix_ui",
    name: "Radix Ui",
    badge: "radix_ui.svg",
    icon: "radix-icon.svg",
    category: "Frontend",
    tags: ["radix_ui", "frontend"],
  },
  {
    id: "redux_saga",
    name: "Redux Saga",
    badge: "redux_saga.svg",
    icon: "reduxsaga-icon.svg",
    category: "Frontend",
    tags: ["redux_saga", "frontend"],
  },
  {
    id: "react_hook_form",
    name: "React Hook Form",
    badge: "react_hook_form.svg",
    icon: "reacthookform-icon.svg",
    category: "Frontend",
    tags: ["react_hook_form", "frontend"],
  },
  {
    id: "react_query",
    name: "React Query",
    badge: "react_query.svg",
    icon: "reactquery-icon.svg",
    category: "Frontend",
    tags: ["react_query", "frontend"],
  },
  {
    id: "rtk_query",
    name: "Rtk Query",
    badge: "rtk_query.svg",
    icon: "redux-icon.svg",
    category: "Frontend",
    tags: ["rtk_query", "frontend"],
  },
  {
    id: "react_select",
    name: "React Select",
    badge: "react_select.svg",
    icon: "react-icon.svg",
    category: "Frontend",
    tags: ["react_select", "frontend"],
  },
  {
    id: "react_datepicker",
    name: "React Datepicker",
    badge: "react_datepicker.svg",
    icon: "react-icon.svg",
    category: "Frontend",
    tags: ["react_datepicker", "frontend"],
  },
  {
    id: "apexcharts",
    name: "Apexcharts",
    badge: "apexcharts.svg",
    icon: "apexcharts-icon.svg",
    category: "Frontend",
    tags: ["apexcharts", "frontend"],
  },
  {
    id: "sql",
    name: "Sql",
    badge: "sql.svg",
    icon: "sql-icon.svg",
    category: "Languages & Scripting",
    tags: ["sql", "languagesscripting"],
  },
  {
    id: "json",
    name: "Json",
    badge: "json.svg",
    icon: "json-icon.svg",
    category: "Languages & Scripting",
    tags: ["json", "languagesscripting"],
  },
  {
    id: "yaml",
    name: "Yaml",
    badge: "yaml.svg",
    icon: "yaml-icon.svg",
    category: "Languages & Scripting",
    tags: ["yaml", "languagesscripting"],
  },
  {
    id: "xml",
    name: "Xml",
    badge: "xml.svg",
    icon: "xml-icon.svg",
    category: "Languages & Scripting",
    tags: ["xml", "languagesscripting"],
  },
  {
    id: "bash",
    name: "Bash",
    badge: "bash.svg",
    icon: "bash-icon.svg",
    category: "Languages & Scripting",
    tags: ["bash", "languagesscripting"],
  },
  {
    id: "zsh",
    name: "Zsh",
    badge: "zsh.svg",
    icon: "zsh-icon.svg",
    category: "Languages & Scripting",
    tags: ["zsh", "languagesscripting"],
  },
  {
    id: "powershell",
    name: "Powershell",
    badge: "powershell.svg",
    icon: "powershell-icon.svg",
    category: "Languages & Scripting",
    tags: ["powershell", "languagesscripting"],
  },
  {
    id: "rest_api",
    name: "Rest Api",
    badge: "rest_api.svg",
    icon: "rest-api-icon.svg",
    category: "Backend",
    tags: ["rest_api", "backend"],
  },
  {
    id: "api_integration",
    name: "Api Integration",
    badge: "api_integration.svg",
    icon: "api-integration-icon.svg",
    category: "Backend",
    tags: ["api_integration", "backend"],
  },
  {
    id: "webhooks",
    name: "Webhooks",
    badge: "webhooks.svg",
    icon: "webhooks-icon.svg",
    category: "Backend",
    tags: ["webhooks", "backend"],
  },
  {
    id: "serverless",
    name: "Serverless",
    badge: "serverless.svg",
    icon: "serverless-icon.svg",
    category: "Backend",
    tags: ["serverless", "backend"],
  },
  {
    id: "aws_lambda",
    name: "Aws Lambda",
    badge: "aws_lambda.svg",
    icon: "aws-lambda-icon.svg",
    category: "Backend",
    tags: ["aws_lambda", "backend"],
  },
  {
    id: "soap",
    name: "Soap",
    badge: "soap.svg",
    icon: "soap-icon.svg",
    category: "Backend",
    tags: ["soap", "backend"],
  },
  {
    id: "azure_functions",
    name: "Azure Functions",
    badge: "azure_functions.svg",
    icon: "azure-functions-icon.svg",
    category: "Backend",
    tags: ["azure_functions", "backend"],
  },
  {
    id: "bcryptjs",
    name: "Bcryptjs",
    badge: "bcryptjs.svg",
    icon: "bcryptjs-icon.svg",
    category: "Backend",
    tags: ["bcryptjs", "backend"],
  },
  {
    id: "express",
    name: "Express",
    badge: "express.svg",
    icon: "express-icon.svg",
    category: "Backend",
    tags: ["express", "backend"],
  },
  {
    id: "passport",
    name: "Passport",
    badge: "passport.svg",
    icon: "passport-icon.svg",
    category: "Backend",
    tags: ["passport", "backend"],
  },
  {
    id: "rxjs",
    name: "Rxjs",
    badge: "rxjs.svg",
    icon: "rxjs-icon.svg",
    category: "Backend",
    tags: ["rxjs", "backend"],
  },
  {
    id: "jest",
    name: "Jest",
    badge: "jest.svg",
    icon: "jest-icon.svg",
    category: "Backend",
    tags: ["jest", "backend"],
  },
  {
    id: "zod",
    name: "Zod",
    badge: "zod.svg",
    icon: "zod-icon.svg",
    category: "UI Tools",
    tags: ["zod", "uitools"],
  },
  {
    id: "yup",
    name: "Yup",
    badge: "yup.svg",
    icon: "yup-icon.svg",
    category: "UI Tools",
    tags: ["yup", "uitools"],
  },
  {
    id: "boto3",
    name: "Boto3",
    badge: "boto3.svg",
    icon: "boto3-icon.svg",
    category: "Backend",
    tags: ["boto3", "backend"],
  },
  {
    id: "opentelemetry",
    name: "Opentelemetry",
    badge: "opentelemetry.svg",
    icon: "opentelemetry-icon.svg",
    category: "Backend",
    tags: ["opentelemetry", "backend"],
  },
  {
    id: "bullmq",
    name: "Bullmq",
    badge: "bullmq.svg",
    icon: "bullmq-icon.svg",
    category: "Backend",
    tags: ["bullmq", "backend"],
  },
  {
    id: "exceljs",
    name: "Exceljs",
    badge: "exceljs.svg",
    icon: "exceljs-icon.svg",
    category: "Backend",
    tags: ["exceljs", "backend"],
  },
  {
    id: "pdfkit",
    name: "Pdfkit",
    badge: "pdfkit.svg",
    icon: "pdfkit-icon.svg",
    category: "Backend",
    tags: ["pdfkit", "backend"],
  },
  {
    id: "pdfmake",
    name: "Pdfmake",
    badge: "pdfmake.svg",
    icon: "pdfmake-icon.svg",
    category: "Backend",
    tags: ["pdfmake", "backend"],
  },
  {
    id: "xlsx",
    name: "Xlsx",
    badge: "xlsx.svg",
    icon: "xlsx-icon.svg",
    category: "Backend",
    tags: ["xlsx", "backend"],
  },
  {
    id: "uuid",
    name: "Uuid",
    badge: "uuid.svg",
    icon: "uuid-icon.svg",
    category: "Backend",
    tags: ["uuid", "backend"],
  },
  {
    id: "sanitize_html",
    name: "Sanitize Html",
    badge: "sanitize_html.svg",
    icon: "sanitize-html-icon.svg",
    category: "Backend",
    tags: ["sanitize_html", "backend"],
  },
  {
    id: "multer",
    name: "Multer",
    badge: "multer.svg",
    icon: "multer-icon.svg",
    category: "Backend",
    tags: ["multer", "backend"],
  },
  {
    id: "mongoose",
    name: "Mongoose",
    badge: "mongoose.svg",
    icon: "mongoose-icon.svg",
    category: "Backend",
    tags: ["mongoose", "backend"],
  },
  {
    id: "drizzle_orm",
    name: "Drizzle Orm",
    badge: "drizzle_orm.svg",
    icon: "drizzle-orm-icon.svg",
    category: "Databases",
    tags: ["drizzle_orm", "databases"],
  },
  {
    id: "git",
    name: "Git",
    badge: "git.svg",
    icon: "git-icon.svg",
    category: "Tools & Development",
    tags: ["git", "toolsdevelopment"],
  },
  {
    id: "github",
    name: "GitHub",
    badge: "github.svg",
    icon: "github-icon.svg",
    category: "Tools & Development",
    tags: ["github", "toolsdevelopment"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    badge: "gitlab.svg",
    icon: "gitlab-icon.svg",
    category: "Tools & Development",
    tags: ["gitlab", "toolsdevelopment"],
  },
  {
    id: "vscode",
    name: "VS Code",
    badge: "vscode.svg",
    icon: "vscode-icon.svg",
    category: "Tools & Development",
    tags: ["vscode", "toolsdevelopment"],
  },
  {
    id: "pnpm",
    name: "Pnpm",
    badge: "pnpm.svg",
    icon: "pnpm-icon.svg",
    category: "Tools & Development",
    tags: ["pnpm", "toolsdevelopment"],
  },
  {
    id: "npm",
    name: "Npm",
    badge: "npm.svg",
    icon: "npm-icon.svg",
    category: "Tools & Development",
    tags: ["npm", "toolsdevelopment"],
  },
  {
    id: "bun",
    name: "Bun",
    badge: "bun.svg",
    icon: "bun-icon.svg",
    category: "Uncategorized",
    tags: ["bun", "uncategorized"],
  },
  {
    id: "sonarqube",
    name: "Sonarqube",
    badge: "sonarqube.svg",
    icon: "sonarqube-icon.svg",
    category: "Tools & Development",
    tags: ["sonarqube", "toolsdevelopment"],
  },
  {
    id: "sonarlint",
    name: "Sonarlint",
    badge: "sonarlint.svg",
    icon: "sonarlint-icon.svg",
    category: "Uncategorized",
    tags: ["sonarlint", "uncategorized"],
  },
  {
    id: "postman",
    name: "Postman",
    badge: "postman.svg",
    icon: "postman-icon.svg",
    category: "Tools & Development",
    tags: ["postman", "toolsdevelopment"],
  },
  {
    id: "linux",
    name: "Linux",
    badge: "linux.svg",
    icon: "linux-icon.svg",
    category: "Tools & Development",
    tags: ["linux", "toolsdevelopment"],
  },
  {
    id: "windows",
    name: "Windows",
    badge: "windows.svg",
    icon: "windows-icon.svg",
    category: "Tools & Development",
    tags: ["windows", "toolsdevelopment"],
  },
  {
    id: "wsl",
    name: "Wsl",
    badge: "wsl.svg",
    icon: "wsl-icon.svg",
    category: "Tools & Development",
    tags: ["wsl", "toolsdevelopment"],
  },
  {
    id: "eslint",
    name: "Eslint",
    badge: "eslint.svg",
    icon: "eslint-icon.svg",
    category: "Tools & Development",
    tags: ["eslint", "toolsdevelopment"],
  },
  {
    id: "prettier",
    name: "Prettier",
    badge: "prettier.svg",
    icon: "prettier-icon.svg",
    category: "Tools & Development",
    tags: ["prettier", "toolsdevelopment"],
  },
  {
    id: "lefthook",
    name: "Lefthook",
    badge: "lefthook.svg",
    icon: "lefthook-icon.svg",
    category: "Tools & Development",
    tags: ["lefthook", "toolsdevelopment"],
  },
  {
    id: "husky",
    name: "Husky",
    badge: "husky.svg",
    icon: "husky-icon.svg",
    category: "Tools & Development",
    tags: ["husky", "toolsdevelopment"],
  },
  {
    id: "vitest",
    name: "Vitest",
    badge: "vitest.svg",
    icon: "vitest-icon.svg",
    category: "UI Tools",
    tags: ["vitest", "uitools"],
  },
  {
    id: "axios",
    name: "Axios",
    badge: "axios.svg",
    icon: "axios-icon.svg",
    category: "UI Tools",
    tags: ["axios", "uitools"],
  },
  {
    id: "lodash",
    name: "Lodash",
    badge: "lodash.svg",
    icon: "lodash-icon.svg",
    category: "UI Tools",
    tags: ["lodash", "uitools"],
  },
  {
    id: "next_auth",
    name: "Next Auth",
    badge: "next_auth.svg",
    icon: "nextauth-icon.svg",
    category: "UI Tools",
    tags: ["next_auth", "uitools"],
  },
  {
    id: "dayjs",
    name: "Dayjs",
    badge: "dayjs.svg",
    icon: "dayjs-icon.svg",
    category: "UI Tools",
    tags: ["dayjs", "uitools"],
  },
  {
    id: "date_fns",
    name: "Date Fns",
    badge: "date_fns.svg",
    icon: "datefns-icon.svg",
    category: "UI Tools",
    tags: ["date_fns", "uitools"],
  },
  {
    id: "i18next",
    name: "I18next",
    badge: "i18next.svg",
    icon: "i18n-icon.svg",
    category: "UI Tools",
    tags: ["i18next", "uitools"],
  },
  {
    id: "jspdf",
    name: "Jspdf",
    badge: "jspdf.svg",
    icon: "jspdf-icon.svg",
    category: "UI Tools",
    tags: ["jspdf", "uitools"],
  },
  {
    id: "react_quill",
    name: "React Quill",
    badge: "react_quill.svg",
    icon: "react-quill-icon.svg",
    category: "UI Tools",
    tags: ["react_quill", "uitools"],
  },
  {
    id: "react_toastify",
    name: "React Toastify",
    badge: "react_toastify.svg",
    icon: "react-toastify-icon.svg",
    category: "UI Tools",
    tags: ["react_toastify", "uitools"],
  },
  {
    id: "stylis_plugin_rtl",
    name: "Stylis Plugin Rtl",
    badge: "stylis_plugin_rtl.svg",
    icon: "stylis-rtl-icon.svg",
    category: "UI Tools",
    tags: ["stylis_plugin_rtl", "uitools"],
  },
  {
    id: "react_dropzone",
    name: "React Dropzone",
    badge: "react_dropzone.svg",
    icon: "react-dropzone-icon.svg",
    category: "UI Tools",
    tags: ["react_dropzone", "uitools"],
  },
  {
    id: "monaco_editor",
    name: "Monaco Editor",
    badge: "monaco_editor.svg",
    icon: "monaco-editor-icon.svg",
    category: "UI Tools",
    tags: ["monaco_editor", "uitools"],
  },
  {
    id: "react_easy_crop",
    name: "React Easy Crop",
    badge: "react_easy_crop.svg",
    icon: "react-easy-crop-icon.svg",
    category: "UI Tools",
    tags: ["react_easy_crop", "uitools"],
  },
  {
    id: "google_libphonenumber",
    name: "Google Libphonenumber",
    badge: "google_libphonenumber.svg",
    icon: "google-libphonenumber-icon.svg",
    category: "UI Tools",
    tags: ["google_libphonenumber", "uitools"],
  },
  {
    id: "dnd_kit",
    name: "Dnd Kit",
    badge: "dnd_kit.svg",
    icon: "dnd-kit-icon.svg",
    category: "UI Tools",
    tags: ["dnd_kit", "uitools"],
  },
  {
    id: "emotion_react",
    name: "Emotion React",
    badge: "emotion_react.svg",
    icon: "emotion-react-icon.svg",
    category: "UI Tools",
    tags: ["emotion_react", "uitools"],
  },
  {
    id: "db",
    name: "Db",
    badge: "db.svg",
    icon: "db-icon.svg",
    category: "Databases",
    tags: ["db", "databases"],
  },
  {
    id: "cursor",
    name: "Cursor",
    badge: "cursor.svg",
    icon: "cursor-icon.svg",
    category: "Tools & Development",
    tags: ["cursor", "toolsdevelopment"],
  },
  {
    id: "windsurf",
    name: "Windsurf",
    badge: "windsurf.svg",
    icon: "windsurf-icon.svg",
    category: "Tools & Development",
    tags: ["windsurf", "toolsdevelopment"],
  },
  {
    id: "kiro",
    name: "Kiro",
    badge: "kiro.svg",
    icon: "kiro-icon.svg",
    category: "Tools & Development",
    tags: ["kiro", "toolsdevelopment"],
  },
  {
    id: "claude_code",
    name: "Claude Code",
    badge: "claude_code.svg",
    icon: "claude-code-icon.svg",
    category: "Tools & Development",
    tags: ["claude_code", "toolsdevelopment"],
  },
  {
    id: "claude_desktop",
    name: "Claude Desktop",
    badge: "claude_desktop.svg",
    icon: "claude-desktop-icon.svg",
    category: "Tools & Development",
    tags: ["claude_desktop", "toolsdevelopment"],
  },
  {
    id: "codex",
    name: "Codex",
    badge: "codex.svg",
    icon: "codex-icon.svg",
    category: "Tools & Development",
    tags: ["codex", "toolsdevelopment"],
  },
  {
    id: "devin",
    name: "Devin",
    badge: "devin.svg",
    icon: "devin-icon.svg",
    category: "Tools & Development",
    tags: ["devin", "toolsdevelopment"],
  },
  {
    id: "gemini",
    name: "Gemini",
    badge: "gemini.svg",
    icon: "gemini-icon.svg",
    category: "Tools & Development",
    tags: ["gemini", "toolsdevelopment"],
  },
  {
    id: "handlebars",
    name: "Handlebars",
    badge: "handlebars.svg",
    icon: "handlebars-icon.svg",
    category: "Uncategorized",
    tags: ["handlebars", "uncategorized"],
  },
  {
    id: "gemini_cli",
    name: "Gemini Cli",
    badge: "gemini_cli.svg",
    icon: "gemini-cli-icon.svg",
    category: "Tools & Development",
    tags: ["gemini_cli", "toolsdevelopment"],
  },
  {
    id: "claude",
    name: "Claude",
    badge: "claude.svg",
    icon: "claude-icon.svg",
    category: "Tools & Development",
    tags: ["claude", "toolsdevelopment"],
  },
  {
    id: "chatgpt",
    name: "Chatgpt",
    badge: "chatgpt.svg",
    icon: "chatgpt-icon.svg",
    category: "Tools & Development",
    tags: ["chatgpt", "toolsdevelopment"],
  },
  {
    id: "ai_studio",
    name: "Ai Studio",
    badge: "ai_studio.svg",
    icon: "ai-studio-icon.svg",
    category: "Tools & Development",
    tags: ["ai_studio", "toolsdevelopment"],
  },
  {
    id: "antigravity",
    name: "Antigravity",
    badge: "antigravity.svg",
    icon: "antigravity-icon.svg",
    category: "Tools & Development",
    tags: ["antigravity", "toolsdevelopment"],
  },
  {
    id: "antigravity_cli",
    name: "Antigravity Cli",
    badge: "antigravity_cli.svg",
    icon: "antigravity-cli-icon.svg",
    category: "Tools & Development",
    tags: ["antigravity_cli", "toolsdevelopment"],
  },
  {
    id: "django",
    name: "Django",
    badge: "django.svg",
    icon: "django-icon.svg",
    category: "Backend",
    tags: ["django", "backend"],
  },
  {
    id: "flask",
    name: "Flask",
    badge: "flask.svg",
    icon: "flask-icon.svg",
    category: "Backend",
    tags: ["flask", "backend"],
  },
  {
    id: "react_router",
    name: "React Router",
    badge: "react_router.svg",
    icon: "reactrouter-icon.svg",
    category: "Uncategorized",
    tags: ["react_router", "uncategorized"],
  },
  {
    id: "react_spring",
    name: "React Spring",
    badge: "react_spring.svg",
    icon: "reactspring-icon.svg",
    category: "Uncategorized",
    tags: ["react_spring", "uncategorized"],
  },
  {
    id: "markdown",
    name: "Markdown",
    badge: "markdown.svg",
    icon: "markdown-icon.svg",
    category: "Languages & Scripting",
    tags: ["markdown", "languagesscripting"],
  },
  {
    id: "java",
    name: "Java",
    badge: "java.svg",
    icon: "java-icon.svg",
    category: "Uncategorized",
    tags: ["java", "uncategorized"],
  },
  {
    id: "c",
    name: "C",
    badge: "c.svg",
    icon: "c-icon.svg",
    category: "Languages & Scripting",
    tags: ["c", "languagesscripting"],
  },
  {
    id: "cpp",
    name: "Cpp",
    badge: "cpp.svg",
    icon: "cpp-icon.svg",
    category: "Languages & Scripting",
    tags: ["cpp", "languagesscripting"],
  },
  {
    id: "csharp",
    name: "Csharp",
    badge: "csharp.svg",
    icon: "csharp-icon.svg",
    category: "Uncategorized",
    tags: ["csharp", "uncategorized"],
  },
  {
    id: "fsharp",
    name: "Fsharp",
    badge: "fsharp.svg",
    icon: "fsharp-icon.svg",
    category: "Uncategorized",
    tags: ["fsharp", "uncategorized"],
  },
  {
    id: "rust",
    name: "Rust",
    badge: "rust.svg",
    icon: "rust-icon.svg",
    category: "Uncategorized",
    tags: ["rust", "uncategorized"],
  },
  {
    id: "go",
    name: "Go",
    badge: "go.svg",
    icon: "go-icon.svg",
    category: "Uncategorized",
    tags: ["go", "uncategorized"],
  },
  {
    id: "kotlin",
    name: "Kotlin",
    badge: "kotlin.svg",
    icon: "kotlin-icon.svg",
    category: "Uncategorized",
    tags: ["kotlin", "uncategorized"],
  },
  {
    id: "swift",
    name: "Swift",
    badge: "swift.svg",
    icon: "swift-icon.svg",
    category: "Uncategorized",
    tags: ["swift", "uncategorized"],
  },
  {
    id: "dart",
    name: "Dart",
    badge: "dart.svg",
    icon: "dart-icon.svg",
    category: "Uncategorized",
    tags: ["dart", "uncategorized"],
  },
  {
    id: "ruby",
    name: "Ruby",
    badge: "ruby.svg",
    icon: "ruby-icon.svg",
    category: "Uncategorized",
    tags: ["ruby", "uncategorized"],
  },
  {
    id: "php",
    name: "PHP",
    badge: "php.svg",
    icon: "php-icon.svg",
    category: "Uncategorized",
    tags: ["php", "uncategorized"],
  },
  {
    id: "scala",
    name: "Scala",
    badge: "scala.svg",
    icon: "scala-icon.svg",
    category: "Uncategorized",
    tags: ["scala", "uncategorized"],
  },
  {
    id: "r_lang",
    name: "R Lang",
    badge: "r_lang.svg",
    icon: "r-lang-icon.svg",
    category: "Uncategorized",
    tags: ["r_lang", "uncategorized"],
  },
  {
    id: "lua",
    name: "Lua",
    badge: "lua.svg",
    icon: "lua-icon.svg",
    category: "Uncategorized",
    tags: ["lua", "uncategorized"],
  },
  {
    id: "elixir",
    name: "Elixir",
    badge: "elixir.svg",
    icon: "elixir-icon.svg",
    category: "Uncategorized",
    tags: ["elixir", "uncategorized"],
  },
  {
    id: "haskell",
    name: "Haskell",
    badge: "haskell.svg",
    icon: "haskell-icon.svg",
    category: "Uncategorized",
    tags: ["haskell", "uncategorized"],
  },
  {
    id: "perl",
    name: "Perl",
    badge: "perl.svg",
    icon: "perl-icon.svg",
    category: "Uncategorized",
    tags: ["perl", "uncategorized"],
  },
  {
    id: "julia",
    name: "Julia",
    badge: "julia.svg",
    icon: "julia-icon.svg",
    category: "Uncategorized",
    tags: ["julia", "uncategorized"],
  },
  {
    id: "groovy",
    name: "Groovy",
    badge: "groovy.svg",
    icon: "groovy-icon.svg",
    category: "Uncategorized",
    tags: ["groovy", "uncategorized"],
  },
  {
    id: "flutter",
    name: "Flutter",
    badge: "flutter.svg",
    icon: "flutter-icon.svg",
    category: "Uncategorized",
    tags: ["flutter", "uncategorized"],
  },
  {
    id: "expo",
    name: "Expo",
    badge: "expo.svg",
    icon: "expo-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["expo", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "android",
    name: "Android",
    badge: "android.svg",
    icon: "android-icon.svg",
    category: "Uncategorized",
    tags: ["android", "uncategorized"],
  },
  {
    id: "ios",
    name: "Ios",
    badge: "ios.svg",
    icon: "ios-icon.svg",
    category: "Uncategorized",
    tags: ["ios", "uncategorized"],
  },
  {
    id: "capacitor",
    name: "Capacitor",
    badge: "capacitor.svg",
    icon: "capacitor-icon.svg",
    category: "Uncategorized",
    tags: ["capacitor", "uncategorized"],
  },
  {
    id: "vuejs",
    name: "Vue.js",
    badge: "vuejs.svg",
    icon: "vuejs-icon.svg",
    category: "Frontend",
    tags: ["vuejs", "frontend"],
  },
  {
    id: "svelte",
    name: "Svelte",
    badge: "svelte.svg",
    icon: "svelte-icon.svg",
    category: "Uncategorized",
    tags: ["svelte", "uncategorized"],
  },
  {
    id: "astro",
    name: "Astro",
    badge: "astro.svg",
    icon: "astro-icon.svg",
    category: "Uncategorized",
    tags: ["astro", "uncategorized"],
  },
  {
    id: "remix",
    name: "Remix",
    badge: "remix.svg",
    icon: "remix-icon.svg",
    category: "Uncategorized",
    tags: ["remix", "uncategorized"],
  },
  {
    id: "nuxtjs",
    name: "Nuxt.js",
    badge: "nuxtjs.svg",
    icon: "nuxtjs-icon.svg",
    category: "Frontend",
    tags: ["nuxtjs", "frontend"],
  },
  {
    id: "gatsby",
    name: "Gatsby",
    badge: "gatsby.svg",
    icon: "gatsby-icon.svg",
    category: "Uncategorized",
    tags: ["gatsby", "uncategorized"],
  },
  {
    id: "solid",
    name: "Solid",
    badge: "solid.svg",
    icon: "solid-icon.svg",
    category: "Uncategorized",
    tags: ["solid", "uncategorized"],
  },
  {
    id: "three_js",
    name: "Three Js",
    badge: "three_js.svg",
    icon: "three-js-icon.svg",
    category: "Frontend",
    tags: ["three_js", "frontend"],
  },
  {
    id: "wasm",
    name: "Wasm",
    badge: "wasm.svg",
    icon: "wasm-icon.svg",
    category: "Uncategorized",
    tags: ["wasm", "uncategorized"],
  },
  {
    id: "fastapi",
    name: "Fastapi",
    badge: "fastapi.svg",
    icon: "fastapi-icon.svg",
    category: "Backend",
    tags: ["fastapi", "backend"],
  },
  {
    id: "spring_boot",
    name: "Spring Boot",
    badge: "spring_boot.svg",
    icon: "spring-boot-icon.svg",
    category: "Uncategorized",
    tags: ["spring_boot", "uncategorized"],
  },
  {
    id: "laravel",
    name: "Laravel",
    badge: "laravel.svg",
    icon: "laravel-icon.svg",
    category: "Uncategorized",
    tags: ["laravel", "uncategorized"],
  },
  {
    id: "rails",
    name: "Rails",
    badge: "rails.svg",
    icon: "rails-icon.svg",
    category: "Uncategorized",
    tags: ["rails", "uncategorized"],
  },
  {
    id: "phoenix",
    name: "Phoenix",
    badge: "phoenix.svg",
    icon: "phoenix-icon.svg",
    category: "Uncategorized",
    tags: ["phoenix", "uncategorized"],
  },
  {
    id: "hono",
    name: "Hono",
    badge: "hono.svg",
    icon: "hono-icon.svg",
    category: "Uncategorized",
    tags: ["hono", "uncategorized"],
  },
  {
    id: "fastify",
    name: "Fastify",
    badge: "fastify.svg",
    icon: "fastify-icon.svg",
    category: "Backend",
    tags: ["fastify", "backend"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    badge: "graphql.svg",
    icon: "graphql-icon.svg",
    category: "UI Tools",
    tags: ["graphql", "uitools"],
  },
  {
    id: "trpc",
    name: "Trpc",
    badge: "trpc.svg",
    icon: "trpc-icon.svg",
    category: "Uncategorized",
    tags: ["trpc", "uncategorized"],
  },
  {
    id: "azure",
    name: "Azure",
    badge: "azure.svg",
    icon: "azure-icon.svg",
    category: "Uncategorized",
    tags: ["azure", "uncategorized"],
  },
  {
    id: "gcp",
    name: "GCP",
    badge: "gcp.svg",
    icon: "gcp-icon.svg",
    category: "Cloud & DevOps",
    tags: ["gcp", "clouddevops"],
  },
  {
    id: "digitalocean",
    name: "Digitalocean",
    badge: "digitalocean.svg",
    icon: "digitalocean-icon.svg",
    category: "Uncategorized",
    tags: ["digitalocean", "uncategorized"],
  },
  {
    id: "heroku",
    name: "Heroku",
    badge: "heroku.svg",
    icon: "heroku-icon.svg",
    category: "Uncategorized",
    tags: ["heroku", "uncategorized"],
  },
  {
    id: "netlify",
    name: "Netlify",
    badge: "netlify.svg",
    icon: "netlify-icon.svg",
    category: "Cloud & DevOps",
    tags: ["netlify", "clouddevops"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    badge: "cloudflare.svg",
    icon: "cloudflare-icon.svg",
    category: "Cloud & DevOps",
    tags: ["cloudflare", "clouddevops"],
  },
  {
    id: "railway",
    name: "Railway",
    badge: "railway.svg",
    icon: "railway-icon.svg",
    category: "Cloud & DevOps",
    tags: ["railway", "clouddevops"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    badge: "kubernetes.svg",
    icon: "kubernetes-icon.svg",
    category: "Cloud & DevOps",
    tags: ["kubernetes", "clouddevops"],
  },
  {
    id: "jenkins",
    name: "Jenkins",
    badge: "jenkins.svg",
    icon: "jenkins-icon.svg",
    category: "Uncategorized",
    tags: ["jenkins", "uncategorized"],
  },
  {
    id: "circle_ci",
    name: "Circle Ci",
    badge: "circle_ci.svg",
    icon: "circle-ci-icon.svg",
    category: "Uncategorized",
    tags: ["circle_ci", "uncategorized"],
  },
  {
    id: "ansible",
    name: "Ansible",
    badge: "ansible.svg",
    icon: "ansible-icon.svg",
    category: "Cloud & DevOps",
    tags: ["ansible", "clouddevops"],
  },
  {
    id: "nginx",
    name: "Nginx",
    badge: "nginx.svg",
    icon: "nginx-icon.svg",
    category: "Cloud & DevOps",
    tags: ["nginx", "clouddevops"],
  },
  {
    id: "redis",
    name: "Redis",
    badge: "redis.svg",
    icon: "redis-icon.svg",
    category: "Databases",
    tags: ["redis", "databases"],
  },
  {
    id: "mysql",
    name: "MySQL",
    badge: "mysql.svg",
    icon: "mysql-icon.svg",
    category: "Databases",
    tags: ["mysql", "databases"],
  },
  {
    id: "mariadb",
    name: "Mariadb",
    badge: "mariadb.svg",
    icon: "mariadb-icon.svg",
    category: "Uncategorized",
    tags: ["mariadb", "uncategorized"],
  },
  {
    id: "firebase",
    name: "Firebase",
    badge: "firebase.svg",
    icon: "firebase-icon.svg",
    category: "Databases",
    tags: ["firebase", "databases"],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    badge: "elasticsearch.svg",
    icon: "elasticsearch-icon.svg",
    category: "Uncategorized",
    tags: ["elasticsearch", "uncategorized"],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    badge: "neo4j.svg",
    icon: "neo4j-icon.svg",
    category: "Uncategorized",
    tags: ["neo4j", "uncategorized"],
  },
  {
    id: "cassandra",
    name: "Cassandra",
    badge: "cassandra.svg",
    icon: "cassandra-icon.svg",
    category: "Uncategorized",
    tags: ["cassandra", "uncategorized"],
  },
  {
    id: "influxdb",
    name: "Influxdb",
    badge: "influxdb.svg",
    icon: "influxdb-icon.svg",
    category: "Uncategorized",
    tags: ["influxdb", "uncategorized"],
  },
  {
    id: "mssql",
    name: "Mssql",
    badge: "mssql.svg",
    icon: "mssql-icon.svg",
    category: "Databases",
    tags: ["mssql", "databases"],
  },
  {
    id: "s3",
    name: "S3",
    badge: "s3.svg",
    icon: "s3-icon.svg",
    category: "Databases",
    tags: ["s3", "databases"],
  },
  {
    id: "kafka",
    name: "Kafka",
    badge: "kafka.svg",
    icon: "kafka-icon.svg",
    category: "Uncategorized",
    tags: ["kafka", "uncategorized"],
  },
  {
    id: "rabbitmq",
    name: "Rabbitmq",
    badge: "rabbitmq.svg",
    icon: "rabbitmq-icon.svg",
    category: "Cloud & DevOps",
    tags: ["rabbitmq", "clouddevops"],
  },
  {
    id: "mqtt",
    name: "Mqtt",
    badge: "mqtt.svg",
    icon: "mqtt-icon.svg",
    category: "Uncategorized",
    tags: ["mqtt", "uncategorized"],
  },
  {
    id: "cypress",
    name: "Cypress",
    badge: "cypress.svg",
    icon: "cypress-icon.svg",
    category: "Uncategorized",
    tags: ["cypress", "uncategorized"],
  },
  {
    id: "playwright",
    name: "Playwright",
    badge: "playwright.svg",
    icon: "playwright-icon.svg",
    category: "Testing",
    tags: ["playwright", "testing"],
  },
  {
    id: "selenium",
    name: "Selenium",
    badge: "selenium.svg",
    icon: "selenium-icon.svg",
    category: "Uncategorized",
    tags: ["selenium", "uncategorized"],
  },
  {
    id: "mocha",
    name: "Mocha",
    badge: "mocha.svg",
    icon: "mocha-icon.svg",
    category: "Uncategorized",
    tags: ["mocha", "uncategorized"],
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    badge: "puppeteer.svg",
    icon: "puppeteer-icon.svg",
    category: "Testing",
    tags: ["puppeteer", "testing"],
  },
  {
    id: "k6",
    name: "K6",
    badge: "k6.svg",
    icon: "k6-icon.svg",
    category: "Uncategorized",
    tags: ["k6", "uncategorized"],
  },
  {
    id: "storybook",
    name: "Storybook",
    badge: "storybook.svg",
    icon: "storybook-icon.svg",
    category: "Tools & Development",
    tags: ["storybook", "toolsdevelopment"],
  },
  {
    id: "tensorflow",
    name: "Tensorflow",
    badge: "tensorflow.svg",
    icon: "tensorflow-icon.svg",
    category: "Uncategorized",
    tags: ["tensorflow", "uncategorized"],
  },
  {
    id: "pytorch",
    name: "Pytorch",
    badge: "pytorch.svg",
    icon: "pytorch-icon.svg",
    category: "AI & ML",
    tags: ["pytorch", "aiml"],
  },
  {
    id: "langchain",
    name: "Langchain",
    badge: "langchain.svg",
    icon: "langchain-icon.svg",
    category: "Uncategorized",
    tags: ["langchain", "uncategorized"],
  },
  {
    id: "openai_sdk",
    name: "Openai Sdk",
    badge: "openai_sdk.svg",
    icon: "openai-sdk-icon.svg",
    category: "AI & ML",
    tags: ["openai_sdk", "aiml"],
  },
  {
    id: "hugging_face",
    name: "Hugging Face",
    badge: "hugging_face.svg",
    icon: "hugging-face-icon.svg",
    category: "Uncategorized",
    tags: ["hugging_face", "uncategorized"],
  },
  {
    id: "pandas",
    name: "Pandas",
    badge: "pandas.svg",
    icon: "pandas-icon.svg",
    category: "AI & ML",
    tags: ["pandas", "aiml"],
  },
  {
    id: "numpy",
    name: "Numpy",
    badge: "numpy.svg",
    icon: "numpy-icon.svg",
    category: "AI & ML",
    tags: ["numpy", "aiml"],
  },
  {
    id: "scikit_learn",
    name: "Scikit Learn",
    badge: "scikit_learn.svg",
    icon: "scikit-learn-icon.svg",
    category: "Uncategorized",
    tags: ["scikit_learn", "uncategorized"],
  },
  {
    id: "ollama",
    name: "Ollama",
    badge: "ollama.svg",
    icon: "ollama-icon.svg",
    category: "Uncategorized",
    tags: ["ollama", "uncategorized"],
  },
  {
    id: "webpack",
    name: "Webpack",
    badge: "webpack.svg",
    icon: "webpack-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["webpack", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "vite",
    name: "Vite",
    badge: "vite.svg",
    icon: "vite-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["vite", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "rollup",
    name: "Rollup",
    badge: "rollup.svg",
    icon: "rollup-icon.svg",
    category: "Uncategorized",
    tags: ["rollup", "uncategorized"],
  },
  {
    id: "esbuild",
    name: "Esbuild",
    badge: "esbuild.svg",
    icon: "esbuild-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["esbuild", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "babel",
    name: "Babel",
    badge: "babel.svg",
    icon: "babel-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["babel", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "turborepo",
    name: "Turborepo",
    badge: "turborepo.svg",
    icon: "turborepo-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["turborepo", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "nx",
    name: "Nx",
    badge: "nx.svg",
    icon: "nx-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["nx", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "figma",
    name: "Figma",
    badge: "figma.svg",
    icon: "figma-icon.svg",
    category: "Tools & Development",
    tags: ["figma", "toolsdevelopment"],
  },
  {
    id: "framer",
    name: "Framer",
    badge: "framer.svg",
    icon: "framer-icon.svg",
    category: "Uncategorized",
    tags: ["framer", "uncategorized"],
  },
  {
    id: "auth0",
    name: "Auth0",
    badge: "auth0.svg",
    icon: "auth0-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["auth0", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "clerk",
    name: "Clerk",
    badge: "clerk.svg",
    icon: "clerk-icon.svg",
    category: "Uncategorized",
    tags: ["clerk", "uncategorized"],
  },
  {
    id: "keycloak",
    name: "Keycloak",
    badge: "keycloak.svg",
    icon: "keycloak-icon.svg",
    category: "Uncategorized",
    tags: ["keycloak", "uncategorized"],
  },
  {
    id: "jwt",
    name: "Jwt",
    badge: "jwt.svg",
    icon: "jwt-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["jwt", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "deno",
    name: "Deno",
    badge: "deno.svg",
    icon: "deno-icon.svg",
    category: "Uncategorized",
    tags: ["deno", "uncategorized"],
  },
  {
    id: "yarn",
    name: "Yarn",
    badge: "yarn.svg",
    icon: "yarn-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["yarn", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "pip",
    name: "Pip",
    badge: "pip.svg",
    icon: "pip-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["pip", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "maven",
    name: "Maven",
    badge: "maven.svg",
    icon: "maven-icon.svg",
    category: "Uncategorized",
    tags: ["maven", "uncategorized"],
  },
  {
    id: "gradle",
    name: "Gradle",
    badge: "gradle.svg",
    icon: "gradle-icon.svg",
    category: "Uncategorized",
    tags: ["gradle", "uncategorized"],
  },
  {
    id: "composer",
    name: "Composer",
    badge: "composer.svg",
    icon: "composer-icon.svg",
    category: "Uncategorized",
    tags: ["composer", "uncategorized"],
  },
  {
    id: "intellij",
    name: "Intellij",
    badge: "intellij.svg",
    icon: "intellij-icon.svg",
    category: "Uncategorized",
    tags: ["intellij", "uncategorized"],
  },
  {
    id: "webstorm",
    name: "Webstorm",
    badge: "webstorm.svg",
    icon: "webstorm-icon.svg",
    category: "Uncategorized",
    tags: ["webstorm", "uncategorized"],
  },
  {
    id: "xcode",
    name: "Xcode",
    badge: "xcode.svg",
    icon: "xcode-icon.svg",
    category: "Uncategorized",
    tags: ["xcode", "uncategorized"],
  },
  {
    id: "android_studio",
    name: "Android Studio",
    badge: "android_studio.svg",
    icon: "android-studio-icon.svg",
    category: "Uncategorized",
    tags: ["android_studio", "uncategorized"],
  },
  {
    id: "vim",
    name: "Vim",
    badge: "vim.svg",
    icon: "vim-icon.svg",
    category: "Tools & Development",
    tags: ["vim", "toolsdevelopment"],
  },
  {
    id: "neovim",
    name: "Neovim",
    badge: "neovim.svg",
    icon: "neovim-icon.svg",
    category: "Tools & Development",
    tags: ["neovim", "toolsdevelopment"],
  },
  {
    id: "insomnia",
    name: "Insomnia",
    badge: "insomnia.svg",
    icon: "insomnia-icon.svg",
    category: "Uncategorized",
    tags: ["insomnia", "uncategorized"],
  },
  {
    id: "dbeaver",
    name: "Dbeaver",
    badge: "dbeaver.svg",
    icon: "dbeaver-icon.svg",
    category: "Tools & Development",
    tags: ["dbeaver", "toolsdevelopment"],
  },
  {
    id: "venv",
    name: "Venv",
    badge: "venv.svg",
    icon: "venv-icon.svg",
    category: "Build Tools, Auth & Package Managers",
    tags: ["venv", "buildtoolsauthpackagemanagers"],
  },
  {
    id: "v0",
    name: "V0",
    badge: "v0.svg",
    icon: "v0-icon.svg",
    category: "AI & ML",
    tags: ["v0", "aiml"],
  },
];

export const techMap: Record<string, TechItem> = techStack.reduce(
  (acc, curr) => {
    acc[curr.id] = curr;
    return acc;
  },
  {} as Record<string, TechItem>,
);

export const techGroups = Array.from(
  new Set(techStack.map((t) => t.category)),
).map((category) => ({
  title: category,
  keys: techStack.filter((t) => t.category === category).map((t) => t.id),
}));
