import fs from 'fs';
import path from 'path';

const publicDir = path.join(__dirname, '../public');
const badgesDir = path.join(publicDir, 'badges');
const iconsDir = path.join(publicDir, 'icons');
const outputFilePath = path.join(__dirname, '../src/lib/svgBundle.ts');

interface SvgData {
  content: string;
  contentNoDimensions: string;
  width: number;
}

const bundle: Record<string, SvgData> = {};

function processDirectory(dir: string) {
  if (!fs.existsSync(dir)) return;

  const files = fs.readdirSync(dir);
  for (const file of files) {
    if (!file.endsWith('.svg')) continue;

    const filePath = path.join(dir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    
    const cleaned = content.replace(/<\?xml.*?\?>/g, '').trim();
    
    let width = 100;
    const widthMatch = content.match(/<svg[^>]*width="([0-9.]+)"/);
    if (widthMatch) {
      width = parseFloat(widthMatch[1]);
    }

    let noDims = cleaned.replace(/<svg([^>]*)width="[^"]*"/, '<svg$1');
    noDims = noDims.replace(/<svg([^>]*)height="[^"]*"/, '<svg$1');

    bundle[file] = {
      content: cleaned,
      contentNoDimensions: noDims,
      width
    };
  }
}

console.log('Bundling SVGs into memory...');

processDirectory(badgesDir);
processDirectory(iconsDir);

const fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/bundle-svgs.ts

export const svgBundle: Record<string, { content: string; contentNoDimensions: string; width: number }> = ${JSON.stringify(bundle, null, 2)};
`;

fs.writeFileSync(outputFilePath, fileContent, 'utf8');
console.log(`Successfully bundled ${Object.keys(bundle).length} SVGs into src/lib/svgBundle.ts`);
